In [1]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()

In [2]:
import pandas as pd
df = pd.DataFrame(cancer.data)
df2 = pd.DataFrame(cancer.target)

In [3]:
cancer.target_names

array(['malignant', 'benign'], dtype='<U9')

In [4]:
df3 = pd.concat([df,df2],axis=1)

In [5]:
df3.head()

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,0
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [6]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
df2.head()

   0
0  0
1  0
2  0
3  0
4  0

In [7]:
cancer.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [8]:
cancer.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [9]:
type(cancer)

sklearn.utils.Bunch

In [10]:
cancer.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

In [11]:
df3.describe().T

,count,mean,std,min,25%,50%,75%,max
0,569.0,14.127292,3.524049,6.981000,11.700000,13.370000,15.780000,28.11000
1,569.0,19.289649,4.301036,9.710000,16.170000,18.840000,21.800000,39.28000
2,569.0,91.969033,24.298981,43.790000,75.170000,86.240000,104.100000,188.50000
3,569.0,654.889104,351.914129,143.500000,420.300000,551.100000,782.700000,2501.00000
4,569.0,0.096360,0.014064,0.052630,0.086370,0.095870,0.105300,0.16340
5,569.0,0.104341,0.052813,0.019380,0.064920,0.092630,0.130400,0.34540
6,569.0,0.088799,0.079720,0.000000,0.029560,0.061540,0.130700,0.42680
7,569.0,0.048919,0.038803,0.000000,0.020310,0.033500,0.074000,0.20120
8,569.0,0.181162,0.027414,0.106000,0.161900,0.179200,0.195700,0.30400
9,569.0,0.062798,0.007060,0.049960,0.057700,0.061540,0.066120,0.09744
10,569.0,0.405172,0.277313,0.111500,0.232400,0.324200,0.478900,2.87300
11,569.0,1.216853,0.551648,0.360200,0.833900,1.108000,1.474000,4.88500
12,569.0,2.866059,2.021855,0.757000,1.606000,2.287000,3.357000,21.98000
13,569.0,40.337079,45.491006,6.802000,17.850000,24.530000,45.190000,542.20000
14,569.0,0.007041,0.003003,0.001713,0.005169,0.006380,0.008146,0.03113
15,569.0,0.025478,0.017908,0.002252,0.013080,0.020450,0.032450,0.13540
16,569.0,0.031894,0.030186,0.000000,0.015090,0.025890,0.042050,0.39600
17,569.0,0.011796,0.006170,0.000000,0.007638,0.010930,0.014710,0.05279
18,569.0,0.020542,0.008266,0.007882,0.015160,0.018730,0.023480,0.07895
19,569.0,0.003795,0.002646,0.000895,0.002248,0.003187,0.004558,0.02984
20,569.0,16.269190,4.833242,7.930000,13.010000,14.970000,18.790000,36.04000
21,569.0,25.677223,6.146258,12.020000,21.080000,25.410000,29.720000,49.54000
22,569.0,107.261213,33.602542,50.410000,84.110000,97.660000,125.400000,251.20000
23,569.0,880.583128,569.356993,185.200000,515.300000,686.500000,1084.000000,4254.00000
24,569.0,0.132369,0.022832,0.071170,0.116600,0.131300,0.146000,0.22260
25,569.0,0.254265,0.157336,0.027290,0.147200,0.211900,0.339100,1.05800
26,569.0,0.272188,0.208624,0.000000,0.114500,0.226700,0.382900,1.25200
27,569.0,0.114606,0.065732,0.000000,0.064930,0.099930,0.161400,0.29100
28,569.0,0.290076,0.061867,0.156500,0.250400,0.282200,0.317900,0.66380
29,569.0,0.083946,0.018061,0.055040,0.071460,0.080040,0.092080,0.20750
0,569.0,0.627417,0.483918,0.000000,0.000000,1.000000,1.000000,1.00000

In [12]:
cancer['data'].shape

(569, 30)

In [13]:
X = cancer['data']
y = cancer['target']

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [15]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# Fit only to the training data
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [16]:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [17]:
from sklearn.neural_network import MLPClassifier

In [18]:
mlp = MLPClassifier(hidden_layer_sizes=(10, 5, 2, 4),max_iter=1000)

In [19]:
mlp.fit(X_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(10, 5, 2, 4), learning_rate='constant',
              learning_rate_init=0.001, max_iter=1000, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [20]:
predictions = mlp.predict(X_test)

In [21]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))

[[53  4]
 [ 1 85]]

In [22]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.98      0.93      0.95        57
           1       0.96      0.99      0.97        86

    accuracy                           0.97       143
   macro avg       0.97      0.96      0.96       143
weighted avg       0.97      0.97      0.96       143

In [23]:
len(mlp.coefs_)

5

In [24]:
mlp.coefs_[0]

array([[-0.26012034,  0.62569793,  0.00725434, -0.3323015 , -0.33685335,
         0.26975677,  0.3417402 ,  0.15050751,  0.16029638,  0.01460015],
       [ 0.10841831,  0.34161566, -0.11484122,  0.4496674 ,  0.40811823,
         0.43439631, -0.28883629,  0.12552531, -0.21777255, -0.01415554],
       [-0.24498418,  0.48770542,  0.19976245,  0.38799747, -0.32034583,
         0.49258642,  0.27084711,  0.13457236, -0.25980933, -0.01684448],
       [ 0.19317123,  0.30445123, -0.41207214,  0.36530553, -0.27095146,
         0.43411962,  0.32205978, -0.35223357, -0.08848048,  0.24582441],
       [-0.08110193, -0.03354628,  0.25128315,  0.17444433,  0.33120537,
         0.38208126, -0.33659987,  0.11439481, -0.02055156,  0.00650021],
       [ 0.44077724,  0.53349624, -0.07642264,  0.29093321,  0.21915521,
        -0.03369221, -0.21717568, -0.3870804 , -0.35537641,  0.03877501],
       [ 0.15634664,  0.70445113,  0.08152925,  0.40692477,  0.20894553,
        -0.03382662,  0.01814001,  0.15514456, -0.45042281, -0.03965933],
       [-0.25196191,  0.24171469, -0.00635647, -0.08337458,  0.04094588,
        -0.12920623, -0.00625702,  0.06643013, -0.43903428,  0.33852082],
       [-0.47521383, -0.0065829 ,  0.16388838, -0.094385  , -0.26672132,
        -0.06255534,  0.01270558, -0.0099535 , -0.16790213,  0.30302045],
       [ 0.20847574, -0.46832642,  0.0232243 , -0.006635  ,  0.36074675,
        -0.20174183,  0.16183125,  0.05727563, -0.29768319, -0.12661547],
       [-0.29134218,  0.33757513,  0.09012473,  0.47524467, -0.12588007,
         0.41525328, -0.21283331, -0.19169633, -0.00799974, -0.14209524],
       [ 0.07322322, -0.14076638,  0.13105018, -0.04693711,  0.31184573,
         0.11951212,  0.10772173, -0.27852358,  0.29052491,  0.29257543],
       [ 0.23496437, -0.04380653, -0.14868871,  0.19360368, -0.35567841,
        -0.0070841 , -0.40233033, -0.10078602, -0.1331191 ,  0.02910166],
       [ 0.11711452,  0.38823372, -0.18830554, -0.0611557 , -0.23470565,
        -0.04668003, -0.04858996,  0.33542378,  0.0387217 ,  0.33244036],
       [-0.22994226,  0.21832661,  0.06024364, -0.2138228 , -0.06300493,
         0.14447942, -0.22126853,  0.03871504,  0.2140662 , -0.17966276],
       [ 0.3800366 , -0.25137202,  0.00154849, -0.34451708,  0.30676955,
         0.23208865, -0.28646816, -0.17444237, -0.34038649, -0.01418742],
       [-0.13973465, -0.01606779,  0.13678635, -0.0028759 ,  0.07521573,
        -0.13534695,  0.11045033, -0.21559471, -0.11596802, -0.18323828],
       [-0.30024536,  0.06446471, -0.10739829,  0.24608984,  0.00416164,
        -0.06505464, -0.06077022, -0.01158589, -0.01305372, -0.20956646],
       [-0.21600138,  0.33661066,  0.07680919, -0.28257405,  0.01329264,
        -0.14978112, -0.20593672,  0.09572659, -0.02844605,  0.22843768],
       [-0.00152799, -0.22688848, -0.11451721, -0.23327435, -0.10430588,
        -0.38854382, -0.0382872 ,  0.09114791, -0.40801326, -0.35331171],
       [-0.0674571 ,  0.54453787, -0.27633279,  0.32590095,  0.25095228,
         0.10049267, -0.15885352, -0.11065237, -0.50510662, -0.01967933],
       [ 0.00896648,  0.50790102, -0.18149833,  0.12981609, -0.20895496,
         0.10858391, -0.17136482,  0.00134446, -0.5169274 , -0.01728538],
       [-0.51166665,  0.257553  , -0.26223867,  0.38586488, -0.24330344,
         0.37745574, -0.47209224,  0.09603177, -0.23707562, -0.07477624],
       [-0.09175617,  0.45390738, -0.20872267,  0.07081281, -0.38291183,
         0.48260783, -0.43604178,  0.02986397, -0.01583177, -0.06653816],
       [-0.15716542,  0.35791441,  0.11956106,  0.32222207,  0.07885892,
         0.45047068,  0.07533416, -0.15651928,  0.16060485,  0.44631904],
       [ 0.00141758,  0.02784299,  0.27562564, -0.04099352,  0.16892257,
        -0.11151204,  0.20788338, -0.22923311, -0.11556844,  0.30281176],
       [-0.3355049 ,  0.44647449, -0.53563391,  0.07648009,  0.22785063,
         0.397377  , -0.361701  ,  0.28708929, -0.02662733,  0.39937935],
       [-0.05507556,  0.07761435,  0.19016336,  0.39416142,  0.06744223,
        -0.01792267, -0.41070678, -0.28087668, -0.3583393 , -0.01778767],
       [-0.00706106,  0.5013295 , -0.01368482,  0.23862848, -0.09835957,
        -0.10984717, -0.18802594,  0.26304465, -0.30780932, -0.02171479],
       [ 0.16566972,  0.18277142,  0.00797882,  0.24164559,  0.26144566,
        -0.02793457,  0.03937751, -0.25573813,  0.05499996,  0.32823992]])

In [25]:
#######################################
# for the sport, what is the CM for RF?

In [26]:
mlp.coefs_[1]

array([[ 0.52515415,  0.55935974,  0.38906606, -0.35844306, -0.41827681],
       [-0.36341524, -0.04303514,  0.13435157,  0.43327799, -0.08152191],
       [ 0.21943947, -0.45514438, -0.01487322, -0.38628968, -0.31126465],
       [-0.73202213, -0.56888618, -0.42465882,  0.22195244, -0.03780357],
       [ 0.64443398, -0.1557664 ,  0.30798553,  0.62795756, -0.094747  ],
       [-0.45917473, -0.54286537, -0.35004093,  0.75279255, -0.52893924],
       [ 0.70117795,  0.04795489,  0.34039139, -0.55047197, -0.49320778],
       [-0.20090819, -0.20059487, -0.58312902, -0.06572623,  0.32730604],
       [ 0.24082797, -0.48604673,  0.6117477 , -0.0731968 , -0.55932642],
       [-0.4275213 ,  0.05718005, -0.18346495,  0.59387194, -0.61466379]])

In [27]:
from sklearn.ensemble import RandomForestClassifier

In [28]:
rf = RandomForestClassifier(random_state=47)
rf.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=47, verbose=0,
                       warm_start=False)

In [29]:
y_pred = rf.predict(X_test)

In [30]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[52  5]
 [ 0 86]]

In [31]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.91      0.95        57
           1       0.95      1.00      0.97        86

    accuracy                           0.97       143
   macro avg       0.97      0.96      0.96       143
weighted avg       0.97      0.97      0.96       143